-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_flagsId_fkey";

-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_sessionsId_fkey";

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "moneySaved" DROP NOT NULL,
ALTER COLUMN "moneySaved" DROP DEFAULT,
ALTER COLUMN "salary" DROP NOT NULL,
ALTER COLUMN "salary" DROP DEFAULT,
ALTER COLUMN "totalExpenses" DROP NOT NULL,
ALTER COLUMN "totalExpenses" DROP DEFAULT,
ALTER COLUMN "totalSpent" DROP NOT NULL,
ALTER COLUMN "totalSpent" DROP DEFAULT,
ALTER COLUMN "flagsId" DROP NOT NULL,
ALTER COLUMN "sessionsId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_sessionsId_fkey" FOREIGN KEY ("sessionsId") REFERENCES "Sessions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_flagsId_fkey" FOREIGN KEY ("flagsId") REFERENCES "Flags"("id") ON DELETE SET NULL ON UPDATE CASCADE;
